//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeyRecord.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class KeyMouse
    {
        public long ID { get; set; }
        public string DeviceName { get; set; }
        public string KeyData { get; set; }
        public Nullable<long> LocationX { get; set; }
        public Nullable<long> LocationY { get; set; }
        public string Title { get; set; }
        public string ClassName { get; set; }
        public string ProcessPath { get; set; }
        public Nullable<System.DateTime> ExecuteDate { get; set; }
        public string ExtendedValue { get; set; }
    }
}
